@LearningASPNET_HostAddress = http://localhost:5030

GET {{LearningASPNET_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{LearningASPNET_HostAddress}}/pizza/
Accept: application/json

###

GET {{LearningASPNET_HostAddress}}/pizza/1
Accept: application/json\

###

GET {{LearningASPNET_HostAddress}}/pizza/5
Accept: application/json

###

POST {{LearningASPNET_HostAddress}}/pizza
Content-Type: application/json

{
    "name": "Hawaii",
    "isGlutenFree": false
}

###

GET {{LearningASPNET_HostAddress}}/pizza/3
Accept: application/json

###

PUT {{LearningASPNET_HostAddress}}/pizza/3
Content-Type: application/json

{
    "id": 3,
    "name": "Hawaiian",
    "isGlutenFree": false
}

###

DELETE {{LearningASPNET_HostAddress}}/pizza/3

###